name: Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choisir l'environnement à déployer"
        required: true
        default: "preprod"
        type: choice
        options:
          - prod
          - preprod

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Docker login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/tcgpocketdex:${{ github.event.inputs.environment }}
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/tcgpocketdex/api
            docker compose pull api_${{ github.event.inputs.environment }}
            docker compose up -d api_${{ github.event.inputs.environment }}
