name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        run: echo "IMAGE_ID=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Preprod image
        run: |
          docker build -t $IMAGE_ID:preprod .
          docker push $IMAGE_ID:preprod

      - name: Build and push Prod image
        run: |
          docker build -t $IMAGE_ID:prod .
          docker push $IMAGE_ID:prod

  deploy-preprod:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy Preprod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/stacks/api
            docker compose pull api-preprod
            docker compose up -d api-preprod

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-preprod

    steps:
      - name: Deploy Prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/stacks/api
            docker compose pull api-prod
            docker compose up -d api-prod
