name: Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choisir l'environnement à déployer"
        required: true
        default: "preprod"
        type: choice
        options:
          - prod
          - preprod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Docker login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/tcgpocketdex:${{ github.event.inputs.environment }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/tcgpocketdex:${{ github.event.inputs.environment }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/tcgpocketdex/api
            docker compose pull api_${{ github.event.inputs.environment }}
            docker compose up -d api_${{ github.event.inputs.environment }}
