name: Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choisir l'environnement à déployer"
        required: true
        default: "preprod"
        type: choice
        options:
          - preprod
          - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        run: echo "IMAGE_ID=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          docker build -t $IMAGE_ID:${{ github.event.inputs.environment }} .
          docker push $IMAGE_ID:${{ github.event.inputs.environment }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/stacks/api
            docker compose pull api-${{ github.event.inputs.environment }}
            docker compose up -d api-${{ github.event.inputs.environment }}
