name: Test SSH Connection

on:
  workflow_dispatch: # permet de lancer manuellement le test depuis l'onglet "Actions"

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "✅ Connexion réussie sur $(hostname)"
            uname -a
            whoami
